"""initial schema

Revision ID: c1b0957b4d6c
Revises:
Create Date: 2026-07-15 10:18:51.794434
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1b0957b4d6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('yeastar_uid', sa.String(length=255), nullable=False),
    sa.Column('yeastar_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('caller_number', sa.String(length=128), nullable=True),
    sa.Column('caller_name', sa.String(length=255), nullable=True),
    sa.Column('callee_number', sa.String(length=128), nullable=True),
    sa.Column('callee_name', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', 'INTERNAL', 'UNKNOWN', name='direction', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('call_status', sa.String(length=64), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.String(length=255), nullable=True),
    sa.Column('has_recording', sa.Boolean(), nullable=False),
    sa.Column('was_transferred', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(length=64), nullable=False),
    sa.Column('last_error_category', sa.String(length=128), nullable=True),
    sa.Column('last_error_message', sa.String(length=1000), nullable=True),
    sa.Column('provider_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls')),
    sa.UniqueConstraint('yeastar_uid', name=op.f('uq_calls_yeastar_uid'))
    )
    op.create_index(op.f('ix_calls_call_status'), 'calls', ['call_status'], unique=False)
    op.create_index(op.f('ix_calls_direction'), 'calls', ['direction'], unique=False)
    op.create_index(op.f('ix_calls_has_recording'), 'calls', ['has_recording'], unique=False)
    op.create_index(op.f('ix_calls_processing_status'), 'calls', ['processing_status'], unique=False)
    op.create_index(op.f('ix_calls_queue_name'), 'calls', ['queue_name'], unique=False)
    op.create_index(op.f('ix_calls_started_at'), 'calls', ['started_at'], unique=False)
    op.create_index('ix_calls_started_at_operator_results', 'calls', ['started_at', 'processing_status'], unique=False)
    op.create_index(op.f('ix_calls_yeastar_id'), 'calls', ['yeastar_id'], unique=False)
    op.create_table('keyword_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_keyword_categories_name'))
    )
    op.create_index(op.f('ix_keyword_categories_active'), 'keyword_categories', ['active'], unique=False)
    op.create_index(op.f('ix_keyword_categories_deleted_at'), 'keyword_categories', ['deleted_at'], unique=False)
    op.create_table('operators',
    sa.Column('yeastar_extension_id', sa.String(length=128), nullable=False),
    sa.Column('extension_number', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operators')),
    sa.UniqueConstraint('yeastar_extension_id', name=op.f('uq_operators_yeastar_extension_id'))
    )
    op.create_index(op.f('ix_operators_deleted_at'), 'operators', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_operators_enabled'), 'operators', ['enabled'], unique=False)
    op.create_index('uq_operators_active_extension_number', 'operators', ['extension_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('application_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_application_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_application_settings_key'))
    )
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_action', 'audit_logs', ['created_at', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('call_legs',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('yeastar_leg_id', sa.String(length=255), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('caller_extension_id', sa.String(length=128), nullable=True),
    sa.Column('callee_extension_id', sa.String(length=128), nullable=True),
    sa.Column('caller_number', sa.String(length=128), nullable=True),
    sa.Column('callee_number', sa.String(length=128), nullable=True),
    sa.Column('answered_by_extension_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('talk_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('provider_recording_id', sa.String(length=255), nullable=True),
    sa.Column('provider_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_legs_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_legs')),
    sa.UniqueConstraint('call_id', 'sequence_number', name='uq_call_legs_call_sequence'),
    sa.UniqueConstraint('call_id', 'yeastar_leg_id', name='uq_call_legs_call_provider_leg')
    )
    op.create_index(op.f('ix_call_legs_answered_by_extension_id'), 'call_legs', ['answered_by_extension_id'], unique=False)
    op.create_index(op.f('ix_call_legs_call_id'), 'call_legs', ['call_id'], unique=False)
    op.create_table('keywords',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_phrase', sa.String(length=500), nullable=False),
    sa.Column('normalized_phrase', sa.String(length=500), nullable=False),
    sa.Column('accent_insensitive', sa.Boolean(), nullable=False),
    sa.Column('whole_word', sa.Boolean(), nullable=False),
    sa.Column('exact_phrase', sa.Boolean(), nullable=False),
    sa.Column('fuzzy_match', sa.Boolean(), nullable=False),
    sa.Column('fuzzy_threshold', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='keyword_severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fuzzy_threshold >= 0 AND fuzzy_threshold <= 100', name=op.f('ck_keywords_fuzzy_threshold_range')),
    sa.ForeignKeyConstraint(['category_id'], ['keyword_categories.id'], name=op.f('fk_keywords_category_id_keyword_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('category_id', 'normalized_phrase', name='uq_keyword_category_phrase')
    )
    op.create_index(op.f('ix_keywords_active'), 'keywords', ['active'], unique=False)
    op.create_index(op.f('ix_keywords_category_id'), 'keywords', ['category_id'], unique=False)
    op.create_index(op.f('ix_keywords_deleted_at'), 'keywords', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_keywords_normalized_phrase'), 'keywords', ['normalized_phrase'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'CONNECTING', 'FETCHING_CALLS', 'FETCHING_CALL_DETAILS', 'FINDING_RECORDINGS', 'DOWNLOADING_RECORDINGS', 'INSPECTING_AUDIO', 'EXTRACTING_OPERATOR_AUDIO', 'TRANSCRIBING', 'SEARCHING_KEYWORDS', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', 'CANCELLED', name='processing_job_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=True),
    sa.Column('queue_name', sa.String(length=255), nullable=True),
    sa.Column('call_status_filter', sa.String(length=64), nullable=True),
    sa.Column('recording_available', sa.Boolean(), nullable=True),
    sa.Column('include_all_speakers', sa.Boolean(), nullable=False),
    sa.Column('selected_operator_ids', sa.JSON(), nullable=False),
    sa.Column('selected_category_ids', sa.JSON(), nullable=False),
    sa.Column('request_filters', sa.JSON(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=128), nullable=False),
    sa.Column('calls_found', sa.Integer(), nullable=False),
    sa.Column('recordings_found', sa.Integer(), nullable=False),
    sa.Column('calls_completed', sa.Integer(), nullable=False),
    sa.Column('calls_failed', sa.Integer(), nullable=False),
    sa.Column('cancellation_requested', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_category', sa.String(length=128), nullable=True),
    sa.Column('last_error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('date_to > date_from', name=op.f('ck_processing_jobs_valid_date_range')),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name=op.f('ck_processing_jobs_progress_range')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_processing_jobs_requested_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_processing_jobs_idempotency_key'))
    )
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('recordings',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('yeastar_recording_id', sa.String(length=255), nullable=False),
    sa.Column('yeastar_file_name', sa.String(length=512), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_extension', sa.String(length=16), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('channel_count', sa.Integer(), nullable=True),
    sa.Column('codec_name', sa.String(length=64), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('bit_rate_bps', sa.Integer(), nullable=True),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'DOWNLOADING', 'DOWNLOADED', 'INSPECTED', 'COMPLETED', 'FAILED', 'DELETED', name='recording_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('channel_assignment', sa.JSON(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_category', sa.String(length=128), nullable=True),
    sa.Column('last_error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_recordings_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recordings')),
    sa.UniqueConstraint('call_id', 'yeastar_recording_id', name='uq_recording_call_provider_id'),
    sa.UniqueConstraint('storage_key', name=op.f('uq_recordings_storage_key'))
    )
    op.create_index(op.f('ix_recordings_call_id'), 'recordings', ['call_id'], unique=False)
    op.create_index('ix_recordings_sha256_checksum', 'recordings', ['sha256_checksum'], unique=False)
    op.create_index(op.f('ix_recordings_status'), 'recordings', ['status'], unique=False)
    op.create_table('call_participants',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.Column('call_leg_id', sa.Uuid(), nullable=True),
    sa.Column('provider_extension_id', sa.String(length=128), nullable=True),
    sa.Column('provider_extension_number', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('CALLER', 'CALLEE', 'ANSWERING_OPERATOR', 'TRANSFERRED_OPERATOR', 'UNKNOWN', name='participant_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('operator_was_caller', sa.Boolean(), nullable=True),
    sa.Column('operator_was_callee', sa.Boolean(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('participated_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participated_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attribution_source', sa.Enum('YEASTAR_EXTENSION', 'STEREO_CHANNEL', 'OPENAI_DIARIZATION', 'UNKNOWN', 'MANUAL_OVERRIDE', name='participant_attribution_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('attribution_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_participants_call_id_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_leg_id'], ['call_legs.id'], name=op.f('fk_call_participants_call_leg_id_call_legs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_call_participants_operator_id_operators'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_participants')),
    sa.UniqueConstraint('call_id', 'operator_id', 'call_leg_id', 'role', name='uq_participant_call_operator_leg_role')
    )
    op.create_index(op.f('ix_call_participants_call_id'), 'call_participants', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_participants_call_leg_id'), 'call_participants', ['call_leg_id'], unique=False)
    op.create_index(op.f('ix_call_participants_operator_id'), 'call_participants', ['operator_id'], unique=False)
    op.create_index(op.f('ix_call_participants_provider_extension_id'), 'call_participants', ['provider_extension_id'], unique=False)
    op.create_table('keyword_variants',
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('phrase', sa.String(length=500), nullable=False),
    sa.Column('normalized_phrase', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_keyword_variants_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_variants')),
    sa.UniqueConstraint('keyword_id', 'normalized_phrase', name='uq_variant_keyword_phrase')
    )
    op.create_index(op.f('ix_keyword_variants_keyword_id'), 'keyword_variants', ['keyword_id'], unique=False)
    op.create_table('processing_job_items',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'SKIPPED', name='processing_job_item_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('stage', sa.String(length=128), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_category', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_processing_job_items_call_id_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_processing_job_items_job_id_processing_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_processing_job_items_operator_id_operators'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_processing_job_items_recording_id_recordings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_job_items')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_processing_job_items_idempotency_key')),
    sa.UniqueConstraint('job_id', 'call_id', 'operator_id', name='uq_job_item_call_operator')
    )
    op.create_index(op.f('ix_processing_job_items_call_id'), 'processing_job_items', ['call_id'], unique=False)
    op.create_index(op.f('ix_processing_job_items_job_id'), 'processing_job_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_processing_job_items_operator_id'), 'processing_job_items', ['operator_id'], unique=False)
    op.create_index(op.f('ix_processing_job_items_recording_id'), 'processing_job_items', ['recording_id'], unique=False)
    op.create_index(op.f('ix_processing_job_items_status'), 'processing_job_items', ['status'], unique=False)
    op.create_table('sync_runs',
    sa.Column('sync_type', sa.Enum('OPERATORS', 'CALLS', name='sync_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', 'CANCELLED', name='sync_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('processing_job_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_category', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['processing_job_id'], ['processing_jobs.id'], name=op.f('fk_sync_runs_processing_job_id_processing_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_sync_runs_idempotency_key'))
    )
    op.create_index(op.f('ix_sync_runs_processing_job_id'), 'sync_runs', ['processing_job_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    op.create_index(op.f('ix_sync_runs_sync_type'), 'sync_runs', ['sync_type'], unique=False)
    op.create_table('transcripts',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=192), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='transcript_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('processing_duration_seconds', sa.Float(), nullable=True),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.Column('api_usage', sa.JSON(), nullable=True),
    sa.Column('error_category', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_audio_sha256', sa.String(length=64), nullable=False),
    sa.Column('is_diarized', sa.Boolean(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_transcripts_call_id_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_transcripts_operator_id_operators'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_transcripts_recording_id_recordings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcripts')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_transcripts_idempotency_key'))
    )
    op.create_index(op.f('ix_transcripts_call_id'), 'transcripts', ['call_id'], unique=False)
    op.create_index(op.f('ix_transcripts_operator_id'), 'transcripts', ['operator_id'], unique=False)
    op.create_index(op.f('ix_transcripts_recording_id'), 'transcripts', ['recording_id'], unique=False)
    op.create_index(op.f('ix_transcripts_source_audio_sha256'), 'transcripts', ['source_audio_sha256'], unique=False)
    op.create_index(op.f('ix_transcripts_status'), 'transcripts', ['status'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('call_leg_id', sa.Uuid(), nullable=True),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.Column('speaker_label', sa.String(length=128), nullable=False),
    sa.Column('speaker_source', sa.Enum('YEASTAR_EXTENSION', 'STEREO_CHANNEL', 'OPENAI_DIARIZATION', 'UNKNOWN', 'MANUAL_OVERRIDE', name='speaker_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('start_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('end_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('transcription_model', sa.String(length=128), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_seconds >= start_seconds', name=op.f('ck_transcript_segments_segment_time_order')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_transcript_segments_call_id_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['call_leg_id'], ['call_legs.id'], name=op.f('fk_transcript_segments_call_leg_id_call_legs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_transcript_segments_operator_id_operators'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('fk_transcript_segments_transcript_id_transcripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_segments')),
    sa.UniqueConstraint('transcript_id', 'sequence_number', name='uq_segment_transcript_sequence')
    )
    op.create_index(op.f('ix_transcript_segments_call_id'), 'transcript_segments', ['call_id'], unique=False)
    op.create_index(op.f('ix_transcript_segments_call_leg_id'), 'transcript_segments', ['call_leg_id'], unique=False)
    op.create_index(op.f('ix_transcript_segments_operator_id'), 'transcript_segments', ['operator_id'], unique=False)
    op.create_index(op.f('ix_transcript_segments_speaker_source'), 'transcript_segments', ['speaker_source'], unique=False)
    op.create_index(op.f('ix_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False)
    op.create_table('keyword_matches',
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_segment_id', sa.Uuid(), nullable=False),
    sa.Column('original_matched_text', sa.Text(), nullable=False),
    sa.Column('normalized_match', sa.Text(), nullable=False),
    sa.Column('context_before', sa.Text(), nullable=False),
    sa.Column('context_after', sa.Text(), nullable=False),
    sa.Column('start_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('end_seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('match_method', sa.Enum('EXACT_PHRASE', 'WHOLE_WORD', 'VARIANT', 'ORDERED_TERMS', 'FUZZY', name='keyword_match_method', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_seconds >= start_seconds', name=op.f('ck_keyword_matches_match_time_order')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_keyword_matches_call_id_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_keyword_matches_keyword_id_keywords'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_keyword_matches_operator_id_operators'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transcript_segment_id'], ['transcript_segments.id'], name=op.f('fk_keyword_matches_transcript_segment_id_transcript_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_matches')),
    sa.UniqueConstraint('keyword_id', 'transcript_segment_id', 'start_seconds', 'normalized_match', name='uq_match_keyword_segment_position')
    )
    op.create_index(op.f('ix_keyword_matches_call_id'), 'keyword_matches', ['call_id'], unique=False)
    op.create_index(op.f('ix_keyword_matches_keyword_id'), 'keyword_matches', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_matches_operator_id'), 'keyword_matches', ['operator_id'], unique=False)
    op.create_index(op.f('ix_keyword_matches_transcript_segment_id'), 'keyword_matches', ['transcript_segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_matches_transcript_segment_id'), table_name='keyword_matches')
    op.drop_index(op.f('ix_keyword_matches_operator_id'), table_name='keyword_matches')
    op.drop_index(op.f('ix_keyword_matches_keyword_id'), table_name='keyword_matches')
    op.drop_index(op.f('ix_keyword_matches_call_id'), table_name='keyword_matches')
    op.drop_table('keyword_matches')
    op.drop_index(op.f('ix_transcript_segments_transcript_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_speaker_source'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_operator_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_call_leg_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_call_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_transcripts_status'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_source_audio_sha256'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_recording_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_operator_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_call_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_sync_runs_sync_type'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_processing_job_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_processing_job_items_status'), table_name='processing_job_items')
    op.drop_index(op.f('ix_processing_job_items_recording_id'), table_name='processing_job_items')
    op.drop_index(op.f('ix_processing_job_items_operator_id'), table_name='processing_job_items')
    op.drop_index(op.f('ix_processing_job_items_job_id'), table_name='processing_job_items')
    op.drop_index(op.f('ix_processing_job_items_call_id'), table_name='processing_job_items')
    op.drop_table('processing_job_items')
    op.drop_index(op.f('ix_keyword_variants_keyword_id'), table_name='keyword_variants')
    op.drop_table('keyword_variants')
    op.drop_index(op.f('ix_call_participants_provider_extension_id'), table_name='call_participants')
    op.drop_index(op.f('ix_call_participants_operator_id'), table_name='call_participants')
    op.drop_index(op.f('ix_call_participants_call_leg_id'), table_name='call_participants')
    op.drop_index(op.f('ix_call_participants_call_id'), table_name='call_participants')
    op.drop_table('call_participants')
    op.drop_index(op.f('ix_recordings_status'), table_name='recordings')
    op.drop_index('ix_recordings_sha256_checksum', table_name='recordings')
    op.drop_index(op.f('ix_recordings_call_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_keywords_normalized_phrase'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_deleted_at'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_category_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_active'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_call_legs_call_id'), table_name='call_legs')
    op.drop_index(op.f('ix_call_legs_answered_by_extension_id'), table_name='call_legs')
    op.drop_table('call_legs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('application_settings')
    op.drop_table('users')
    op.drop_index('uq_operators_active_extension_number', table_name='operators', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_operators_enabled'), table_name='operators')
    op.drop_index(op.f('ix_operators_deleted_at'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_keyword_categories_deleted_at'), table_name='keyword_categories')
    op.drop_index(op.f('ix_keyword_categories_active'), table_name='keyword_categories')
    op.drop_table('keyword_categories')
    op.drop_index(op.f('ix_calls_yeastar_id'), table_name='calls')
    op.drop_index('ix_calls_started_at_operator_results', table_name='calls')
    op.drop_index(op.f('ix_calls_started_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_queue_name'), table_name='calls')
    op.drop_index(op.f('ix_calls_processing_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_has_recording'), table_name='calls')
    op.drop_index(op.f('ix_calls_direction'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_status'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
